git_url: git@github.com:fclimited/fcl-corporate.git
credentials: 868dff41-ea25-40e0-9f29-69c31e9a4a05
recipients: modmac@gmail.com
report_path: build/*/*.xml,docroot/sites/*/tests/behat/test-report-xml/*.xml,docroot/sites/all/modules/custom/*/tests/behat/test-report-xml/*.xml
pre_build_shell:
  - unlink /data/docroot/web/docroot || true; ln -s ${WORKSPACE}/docroot /data/docroot/web/docroot; mkdir bin; ln -s /var/lib/jenkins/jobs/testing-framework/workspace/bin/behat bin/behat
post_build_shell:
description:  Executing unit tests over and {{branch}} branch
htmlPublishers:
